import express from 'express';
import { Chat } from '../models/Chat.ts';
import { authMiddleware, AuthRequest } from '../middleware/auth.ts';

const router = express.Router();

router.post('/', authMiddleware, async (req: AuthRequest, res) => {
  const { message } = req.body;

  try {
    let chat = await Chat.findOne({ tenantId: req.user.tenantId, userId: req.user._id });
    if (!chat) {
      chat = await Chat.create({
        tenantId: req.user.tenantId,
        userId: req.user._id,
        messages: [],
      });
    }

    const userMessage = { role: 'user', content: message };
    const assistantMessage = {
      role: 'assistant',
      content: `This is a mock AI response to your query: "${message}". In a real implementation, this would be generated by an LLM like Gemini.`,
    };

    chat.messages.push(userMessage);
    chat.messages.push(assistantMessage);
    await chat.save();

    res.json(assistantMessage);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

router.get('/history', authMiddleware, async (req: AuthRequest, res) => {
  try {
    const chat = await Chat.findOne({ tenantId: req.user.tenantId, userId: req.user._id });
    res.json(chat ? chat.messages : []);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

export default router;
